version: '3.7'

services:
  db:
    container_name: "synapsis_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "synapsis_test"
      MYSQL_USER: "synapsis"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name:  "synapsis_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
    volumes:
      - .:/app/

networks:
  default:
volumes:
  mysql_data: